### ISSUE TITLE
xss activity

### ISSUE THREAD

**Issue by fanfare** [oilstel/elliott-social#4]
i noticed on the frontpage there was a missing square

![1584161486 509025](https://user-images.githubusercontent.com/46735339/76675349-407a4780-6586-11ea-976f-b3c723a1ba5e.png)

seems the class 'message' was injected into this user's profile somehow. their page has some xss stuff in it. prob wise idea to escape `< > " ' &` characters.

**Comment by oilstel** [comment]
xss should be escaped now. thanks for opening this issue. i can add a check for shapes in the future. reid was using the message class... tricky
